### ISSUE TITLE
Train from scratch on DISFA

### ISSUE THREAD

**Issue by rafikg** [ZhiwenShao/PyTorch-JAANet#14]
Hi @ZhiwenShao,
I am wondering if you can share the *.pth of BP4D or the parameter that you have used to train the model on DISFA from scratch.
Actually I have just comment this part of code https://github.com/ZhiwenShao/PyTorch-JAANet/blob/5d76a5603184466c4fd64ed1a53431a59728cdd0/train_JAAv1_disfa.py#L64#L9.
Thanks

**Comment by ZhiwenShao** [comment]
I am sorry for the delayed reply, since I'm busy with several schedules recently. The trained models can be found [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/Eu3SDFcZYG9Ah5RdRYqfYxoBWDyWici_FdWJP8TnYFqaZw?e=ogNmZv). The DISFA model is fine-tuned from the BP4D_combine_1_3 model.
