### ISSUE TITLE
The performance of BP4D dataset

### ISSUE THREAD

**Issue by Keysmis** [ZhiwenShao/PyTorch-JAANet#15]
Hi~, firstly, thanks for opening your great work~, recently, we are working on FAU problems, and we follow your readme to train our model on BP4D dataset, but we can't get the result you said in IJCV version, we just got F1-frame about 0.6 in BP4D-part3.
Is there some tracks that you forget to write in Readme? 
Thanks~

**Comment by ZhiwenShao** [comment]
I was busy with several schedules recently. I'm very sorry for the delayed reply. 
We conduct 3-fold cross-validation on BP4D, so the result is the average of three folds rather than only BP4D-part3.
The trained models can be downloaded [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/Eu3SDFcZYG9Ah5RdRYqfYxoBWDyWici_FdWJP8TnYFqaZw?e=ogNmZv).
