### ISSUE TITLE
Output of region_learning is NAN when training BP4D

### ISSUE THREAD

**Issue by yunyunzhong** [ZhiwenShao/PyTorch-JAANet#3]
Hello,Shao!Thank you very much for sharing your code!
I got an issue when training BP4D that the output tensor parameters of region_learning always become NAN(sometimes 0) ,have you ever encountered similar issues？Or,What do you think caused it and how to fix it?
Thanks for the help!

**Comment by ZhiwenShao** [comment]
I have not encounted this issue. I guess the issue is related to the image size and AU/landmark annotations. Could you paste a few AU/landmark annotations here? Besides, I suggest you test a simplified network including the region learning module.

**Comment by yunyunzhong** [comment]
Thank you for your quick reply!
My processed image size is 200*200, and I did not modify any other parameters.
Thank you for your suggestion!
[BP4D_part3_AUoccur的副本.txt](https://github.com/ZhiwenShao/PyTorch-JAANet/files/4425179/BP4D_part3_AUoccur.txt)
[BP4D_part3_land的副本.txt](https://github.com/ZhiwenShao/PyTorch-JAANet/files/4425183/BP4D_part3_land.txt)
[BP4D_part3_path的副本.txt](https://github.com/ZhiwenShao/PyTorch-JAANet/files/4425184/BP4D_part3_path.txt)

**Comment by ZhiwenShao** [comment]
After seeing your files, I find the order in different files are inconsistent.
For F021_T2_1319.jpg, my landmark annotations are:
43.234 41.026 51.742 35.99 61.722 34.888 71.677 35.691 81.984 37.63 115.88 38.432 127.01 35.725 138.27 34.511 149.94 35.826 159.47 41.666 98.622 64.654 98.114 76.098 97.441 87.558 96.774 98.393 86.3 107.48 91.222 109.37 97.032 110.1 103.33 109.6 109.09 108.37 57.344 64.12 64.358 62.37 71.849 62.837 79.29 66.474 71.427 67.965 63.929 67.374 119.62 66.013 126.6 62.166 134.25 62.106 142.51 64.273 135.56 68.091 127.27 68.489 77.977 133.81 82.295 127.58 88.9 122.54 96.868 123.06 105.02 122.56 111.85 127.41 117.71 133.42 113.21 141.43 105.72 146.36 96.331 147.07 87.635 146.36 81.206 141.68 90.136 131.19 97.132 130.15 104.24 131.02 103.93 135.44 96.844 134.36 90.176 134.94
However, your  landmark annotations are:
29.075805	65.268065	36.344756	57.342657	46.728972	55.710956	57.320872	57.342657	67.289720	61.305361	90.550363	59.440559	101.973001	54.778555	113.395639	52.214452	125.233645	53.613054	134.579439	60.839161	79.958463	81.585082	79.750779	94.172494	79.750779	106.060606	79.543094	118.648019	67.912773	128.904429	74.350987	130.069930	80.789200	131.002331	87.435099	129.603730	93.873313	128.671329	42.159917	85.547786	49.013499	83.682984	56.282451	83.449883	63.136033	87.179487	56.282451	88.578089	48.598131	88.578089	99.480789	85.780886	105.919003	81.118881	113.395639	81.118881	121.079958	82.284382	114.641745	85.547786	106.957425	86.480186	63.966771	156.876457	69.366563	148.951049	76.427830	144.755245	80.996885	146.386946	86.396677	144.289044	94.704050	148.717949	102.180685	155.011655	95.327103	164.568765	87.642783	168.997669	81.827622	169.930070	76.635514	169.463869	69.574247	165.501166	76.843198	152.447552	81.412253	152.680653	86.812046	151.981352	86.812046	157.342657	81.412253	158.275058	76.635514	158.041958
So, I think the issue is the images and landmark annoations are non-corresponding.

**Comment by yunyunzhong** [comment]
Thank you so much!
I‘ll check my landmark annotations.

**Comment by PatrykKotlowski** [comment]
I've got related question. What exactly dataset from 
http://www.cs.binghamton.edu/%7Elijun/Research/3DFE/3DFE_Analysis.html
do you use? 
I've got access to the **BP4D-Spontaneous** and i noticed that after running script **face_transform.py** images was rotated by 45 deg (attached image). So maybe that's the problem with Nan error.
It's think landmarks from my dataset is quite different than yours. 
Could you include sample output of **face_transform.py**  script?
![2440](https://user-images.githubusercontent.com/37079300/80470974-07821080-8943-11ea-968d-fa7599641fa5.jpg)

**Comment by ZhiwenShao** [comment]
The official landmark annotations are given by SDM, and contain minor errors. I also find the misaligned images are very low proportion, these images will not cause the NAN issue.

**Comment by PatrykKotlowski** [comment]
I belive we've got a little bit different datasets. As I mentioned in #1 my landmarks are in different files than yours (e.g. in 2DFeatures/F001_T1.mat file).
And in fact all my images processed by **face_transform.py** look like the one I attached in previews post. So I fink although we both have 49-points landmarks, but points numbering may be different. I attach image with my landmarks layout.

![Figure_1](https://user-images.githubusercontent.com/37079300/80475532-4d41d780-8949-11ea-8016-b3c24638ea62.png)

**Comment by yunyunzhong** [comment]
we use the same  dataset.(BP4D-Spontaneous)
Our landmark are different because I have tried two preprocessing methods.
version 1:I used opencv and dlib to process face recognition and crop the facial images of the BP4D dataset and I did't run face_transform.py(no rotated images).
version 2:I Applied Shao's script(face_transform.py) for preprocessing.(few misaligned images)
Shao's right, misaligned images will not cause the NAN issue because version1 and version2 both encountered the NAN issue.And if I only train HierarchicalMultiScaleRegionLayer, the NAN issue did not happen.
By the way, my landmark was not provided by the dataset, I detected the landmarks by Dlib.
F001_T1_2455
![F001_T1_2455](https://user-images.githubusercontent.com/45170325/80477232-2baf1300-897e-11ea-8000-e4ed1b8d7338.jpg)

**Comment by PatrykKotlowski** [comment]
Thank you for answer!
So in the end you was able to create landmarks which doesn't cause Nan error right? 
Could you attach the preprocess script or just give some advice what dblib and opencv functions use to get wanted output?

**Comment by yunyunzhong** [comment]
I used dlib to detect facial landmarks before, maybe you can try new methods.And most detection methods detect 68 points, we need to correspond them to 49 points.
I referenced this script https://github.com/wiibrew/EAC-Net/blob/master/get_face.py to crop face.
<img width="1540" alt="68landmark" src="https://user-images.githubusercontent.com/45170325/80481349-d5919e00-8984-11ea-87d7-62aaa98ddf36.png">
![下载](https://user-images.githubusercontent.com/45170325/80481381-e3dfba00-8984-11ea-87d1-81f8acb4f4cb.png)
I don’t know if it works, but I wish it could help

**Comment by PatrykKotlowski** [comment]
Great! Thank you very much!
I'll let you know if it worked :)

**Comment by PatrykKotlowski** [comment]
Everything works great!
Thank you!
