### ISSUE TITLE
how to access the Pretrained Snapshot?

### ISSUE THREAD

**Issue by hopelyj** [ZhiwenShao/PyTorch-JAANet#5]
Hello,
Thank you  for your shared code. I wonder where can I find the Pretrained snapshot?  Could you please upload the snapshot?

**Comment by ZhiwenShao** [comment]
Thanks very much for your interest in our code. We will release the trained snapshots after our paper is accepted.

**Comment by sjtulh** [comment]
> Thanks very much for your interest in our code. We will release the trained snapshots after our paper is accepted.

Thanks for your code and paper. Could you please upload the snapshot now?

**Comment by gedaye11** [comment]
Hi, Can you reproduce this performance according to Readme to train JAANet-v2 model on the BP4D dataset.
Now I cannot get the results as said in the IJCV version. In BP4D-part3, we only get about F1-frame of 0.6 (decrease about 2.5%) .

**Comment by ZhiwenShao** [comment]
I was busy with several schedules recently. I'm very sorry for the delayed reply. 
We conduct 3-fold cross-validation on BP4D, so the result is the average of three folds rather than only BP4D-part3.
The trained models can be downloaded [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/Eu3SDFcZYG9Ah5RdRYqfYxoBWDyWici_FdWJP8TnYFqaZw?e=ogNmZv).
